### ISSUE TITLE
Link to Behance

### ISSUE THREAD

**Issue by jonahfried** [jonahfried/jonahfried.github.io#11]
I would like a link to my behance :+1:

**Comment by tzierbock** [comment]
Can you give me a link to your profile on Behance. Should I put it with all the other links at the bottom?

**Comment by jonahfried** [comment]
https://www.behance.net/jonahfried

**Comment by jonahfried** [comment]
Yes if the icon could be with the others that would be great :+1:

**Comment by tzierbock** [comment]
https://github.com/jonahfried/jonahfried.github.io/commit/86a7cd98d50225ff87d6c52529ee8c4e6afda7b5
Done
